name: shared_pref_package
description: "A new Flutter package project."
publish_to: none # DON'T REMOVE THIS LINE!
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
