arb-dir: lib/l10n/arb
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/l10n/gen
nullable-getter: false
synthetic-package: false

# Needed to ensure the formatter does not run on the generated files.
header: "// dart format off\n// coverage:ignore-file"