name: app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^16.0.0
  get_it: ^8.0.3


  # Local packages
  theme_package:
    path: ../packages/theme_package
  language_package:
    path: ../packages/language_package
  logging_package:
    path: ../packages/logging_package
    
dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  generate: true
  uses-material-design: true
