name: database_package
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.37
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^8.0.3
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.0
  build_runner: ^2.6.0


flutter:
